### ISSUE TITLE
Capitalization of AutoHotkey is inconsistent

### ISSUE THREAD

**Issue by G33kDude** [ahkscript/awesome-AutoHotkey#27]
There are numerous places where it's written `Autohotkey` instead of `AutoHotkey`. Should these be changed in one fell swoop?

**Comment by joedf** [comment]
Yes, please do! Change all of the different cases (AUTOHOTKEY, AutoHotKey, autohotkey, etc) to AutoHotkey.

**Comment by G33kDude** [comment]
Except for, I assume, urls?

**Comment by joedf** [comment]
Hmm, you're right. :+1:

**Comment by G33kDude** [comment]
I'm a bit unsure whether to correct the capitalization for `Sublime 4 Autohotkey` since it's actually capitalized that way on the forum post. Suggestions?

**Comment by joedf** [comment]
Erhhh... Change it also

**Comment by hi5** [comment]
Sublime 4 Autohotkey should be removed as avi will now contribute to the official SublimeAutoHotkey which is also published on the ST packagecontrol website.

**Comment by joedf** [comment]
Replace with a new link?

**Comment by hi5** [comment]
SublimeAutoHotkey is already there (just above it) it should Sublime 4 Autohotkey just be removed imho.

**Comment by vasili111** [comment]
I have looked at `Sublime 4 Autohotkey` links and did not found anywhere that its development is discontinued. Where **avi** wrote that development of `Sublime 4 Autohotkey` is discontinued? 

If `Sublime 4 Autohotkey` development is discontinued, I think it should be marked as  (discontinued).
If **avi** says that `SublimeAutoHotkey` is continuation of `Sublime 4 Autohotkey` development and currently `SublimeAutoHotkey`  does not have any feature that `SublimeAutoHotkey lucks,  in that case I think it is better to remove `Sublime 4 Autohotkey` link.

**Comment by G33kDude** [comment]
http://www.autohotkey.com/board/topic/91066-sublime-4-autohotkey-updated-1311/?p=580423

>As Sublimetext has gone totally shareware in its version 3.0, i will not develop it anymore.Will not be Updated.

Additionally, it has not been updated in quite some time

**Comment by hi5** [comment]
I inferred that from avis issues / posts here:
https://github.com/ahkscript/SublimeAutoHotkey/issues/15
https://github.com/ahkscript/SublimeAutoHotkey/issues/17
http://www.autohotkey.com/board/topic/91066-sublime-4-autohotkey-updated-1311/?p=684977
http://www.autohotkey.com/board/topic/91066-sublime-4-autohotkey-updated-1311/?p=580423

**Comment by vasili111** [comment]
@G33kDude @hi5 Thanks for the links!
As I understand from the links `SublimeAutoHotkey` is not direct successor of `Sublime 4 Autohotkey`. 
I think it is better to mark it as `discontinued` until it is still usable with current version of Sublime Editor, because someone may prefer to use `Sublime 4 Autohotkey`. When `Sublime 4 Autohotkey` becomes unusable with current version of  Sublime Editor we can remove it. What you what you think about it?
@aviaryan What you think about it?

**Comment by aviaryan** [comment]
@vasili111 Sublime 4 AutoHotkey project is not dead. The reason I am not developing it anymore is I plan to shift the backend from AutoHotkey to Python. That is, all the Su4AHK features will be implemented via Sublime python plugins. This will make the overall experience more smooth.
Yes, if it possible to add all these features inside the `SublimeAutoHotkey` project itself, then I will discontinue the `Sublime4AutoHotkey` and redirect it to this one.

I agree with @vasili111 here that Su4AHK should be removed when it becomes unusable with the latest version of Sublime. Since Sublime hasn't been updated since I started the project, it's safe to keep it currently.

**Comment by joedf** [comment]
SublimeAutohotkey used to be named something else, I had renamed: https://github.com/ahkscript/SublimeAutoHotkey/commit/b00997d760f704039e3efff8ae01bce5e58607af
