### ISSUE TITLE
Add a common use "functions" section

### ISSUE THREAD

**Issue by joedf** [ahkscript/awesome-AutoHotkey#35]
A new 'Functions" section :)
This would fit under it. 
https://github.com/ahkscript/awesome-AutoHotkey/issues/34

**Comment by G33kDude** [comment]
I have a few of my own one-off functions that would fit there. Things like FixIE, that don't really call for a whole library.

**Comment by joedf** [comment]
Hmm sounds perfect

**Comment by vasili111** [comment]
@joedf , @G33kDude, @evilC 

Good idea!
What you think, where exactly it is better to be? Before "Libraries" and "Libraries distributions" or after them?

Also what you think, maybe it is better to put "Library distributions" before "Libraries" or leave as it is?

**Comment by joedf** [comment]
I'm thinking, libraries before lib distros. Sort of a hierarchy order.

**Comment by vasili111** [comment]
@joedf 
So:
* Library Distributions
* Libraries
* Functions
* Scripts
* Tools
* Tutorials
* Resources

Right?

**Comment by G33kDude** [comment]
I was thinking that functions should be a subset of libraries (or perhaps vice versa)

**Comment by joedf** [comment]
Functions first, I'd say... ?

**Comment by hi5** [comment]
Isn't the problem there are literally hundreds of useful functions? That is the problem I face with https://github.com/hi5/pAHKlight as well - could add entries on a daily basis ...

**Comment by joedf** [comment]
Hmm you're right, but I thinking those functions that are only do one thing specially, I'm sure we could find some nice examples

**Comment by G33kDude** [comment]
Is there a way to make collapsible sub-sections in markdown?

**Comment by joedf** [comment]
Eurhh... Not really, unless it's a custom flavoured md :p

**Comment by vasili111** [comment]
```Functions first, I'd say... ?```
@joedf sure :)

<br>

```I was thinking that functions should be a subset of libraries (or perhaps vice versa)```

@G33kDude You mean like this?

- [Libraries](#libraries)
    - [Clipboard](#clipboard)
    - [Console](#console)
    - [Database](#database)
    - [Functions](#functions)
    - [Filesystem](#filesystem)
    - [Graphics](#libraries-graphics)
    - [GUI](#gui)
    - [Hotkeys](#hotkeys)

I dont think it is a good idea because there should be some order for functions too. I think it is better to create separate section for functions which will have corresponding subsections depending on what they do. Like this:

- [Fuctions](#fanctions)
    - [Clipboard](#clipboard)
    - [Console](#console)
    - [Database](#database)
    - [Filesystem](#filesystem)
    - [Graphics](#libraries-graphics)
    - [GUI](#gui)
    - [Hotkeys](#hotkeys)
- [Libraries](#libraries)
    - [Clipboard](#clipboard)
    - [Console](#console)
    - [Database](#database)
    - [Filesystem](#filesystem)
    - [Graphics](#libraries-graphics)
    - [GUI](#gui)
    - [Hotkeys](#hotkeys)


```Is there a way to make collapsible sub-sections in markdown?```
@G33kDude You can use some html in markdown but there are some restrictions. I dont know what are the exact restrictions but you can try to make it with html.

**Comment by rshipp** [comment]
Yeah, you can include HTML in Markdown and use Bootstrap's collapsible divs, like @vasili111 said. That kinda defeats the purpose of using Markdown though, and I'm pretty sure it won't work in a GitHub README, otherwise people would just be able to embed random JS. 

Also, I'm not sure I understand why functions need a separate section. If you put a function in a file, doesn't that make it a library? I'd say it's just a library with only a single function. I don't know of any other language that makes a distinction like this, but maybe I'm just missing something that makes AHK different. ¯\\\_(ツ)\_/¯

**Comment by G33kDude** [comment]
I don't guess they really have to be separate, but would you call a room with a single book in it a library?

**Comment by joedf** [comment]
:p

**Comment by vasili111** [comment]
I like @rshipp ideas. Lets don't separate libraries and functions and use *Libraries* section for functions too. Just put functions in corresponding subsection of *Libraries* section.

**Comment by joedf** [comment]
Right-on! it's settled then. :+1:
