### ISSUE TITLE
Author and state (discontinued) position in item.

### ISSUE THREAD

**Issue by vasili111** [ahkscript/awesome-AutoHotkey#42]
This Issue came from that discussion https://github.com/ahkscript/awesome-AutoHotkey/issues/21#issuecomment-135640172 .

First of all, does we really need to write name of the author? Does it gives any useful information for the reader? Also many item have several authors. I think we should not write author. If we decide to use author I think it should be italic and enclosed by two `-`, like `-`_`author`_`-`. 
What you think about it?

I think it is very important to know if item is discontinued so the reader should get this information in first place. I think `(discontinued)` should come after name (and if we decide to use author, after author too) of the item and should be bold and have `!` sign, like **`(discontinued!)`**. So it should look like:

Without author:
[Item name](Item name) - **(discontinued!)**.  Description and links.

OR

With author:
[Item name](Item name) - _by author_ - **(discontinued!)**.  Description and links.

**Comment by hoppfrosch** [comment]
On Author:
I'm not quite sure: Author does not give huge additional information, but it shows respect to the person who has contributed something awesone to Autohotkey. Therefore they might have deserved being listed with their scripts ....

I would vote to keep *author*

On Discontinued:
English is not my native language . perhaps a native might find a better wording or enlighten me. I would understand "discontinued" as: "this script has stopped being developed". What I would like to see is a word which says "the author said, this script has stopped being developed". Whilst the first may be true for MANY scripts on the page (who knows which of those scripts are still active developed?), it's an absolute truth in the second case. I think, labelling a script  as "stopped being developed" (because the other said this) leads the users attention unjustifiable to other scripts - which also might be not developed any more (but the author didn't say this). As all scripts are possibly discontinued and only some of the authors are so fair to announce this, should only those scripts be stigmatized?
Thinking more about it: everything what's currently considered to be worth to be listed on this page should be in a state where it's mature, usefull and functional. Does it matter in this case, whether the script is discontinued? If there are concerns about the script being discontinued - should it still be worth to be listed on this page? 

I would vote to remove *Discontinued*

**Comment by hoppfrosch** [comment]
Another idea: let's set up a "Historical section" - where awesome scripts are listed which aren't state of the art anymore. Discontinued scripts could be moved there - if they are worth being kept on the awesome list.

**Comment by vasili111** [comment]
>I'm not quite sure: Author does not give huge additional information, but it shows respect to the person who has contributed something awesone to Autohotkey. Therefore they might have deserved being listed with their scripts ....

What about if we put author name at the end of the item in *italic*, like this:

[Item name](Item name) - Description and links. *Developed by author.*

I think it looks better and more structured form and gives first of all useful information to the reader and also states the name of the author. What you think about it?

>Another idea: let's set up a "Historical section" - where awesome scripts are listed which aren't state of the art anymore. Discontinued scripts could be moved there - if they are worth being kept on the awesome list.

Good point! I agree with you. The awesome list should only consist of uptodate and working items. I think it is nice to separate historically important items from others.  What about creating separate "Historical.md" (or suggest other name) with identical structure of awesome list and put all items that are historically valuable items in it?

**Comment by hoppfrosch** [comment]
Sorry for the late answer - was on vacation ;-)

I have no strong feeling about the placement and formatting of the author. One thing I would like to point is, that currently the AAH2html-script (which produces the GH pages) does not support Markdown-formatting very well :-( (this causes to display the italic markup  literally - and not rendered as italic ...)
In my eyes there has to be either the AAH2html-script being refactored or the GH-pages to be removed ...

Good suggestion about the "Historical.md" page .... I would like to see an short introductory text there,  stating the purpose of the page (For example: This page contains awesome AHK-scripts that are no longer state-of-the-art" ...

(Excuse my poor english, as I'm german ;-))

**Comment by hoppfrosch** [comment]
Created #47 to document creation of page "historical.md"

**Comment by MasterFocus** [comment]
I know that fiddling with the format would impact on the AAH2html-script.
Still, I'd like to throw another opinion here. :smile:

Many authors (as well as related developers - often cited in descriptions) do have a GitHub account, like myself, Lexikos, JoeDF, GeekDude and HotKeyIt.

In addition to any formatting ideas, I think It'd be nice if we managed to actually "mention" them.
(like this: @MasterFocus)

**Comment by hi5** [comment]
1. Personally I would remove the authors (by ...) as I don't think it holds useful information and 9 out 10 times it will be pretty obvious once you follow the link to the program/forum or GH repo. 
2. The HTML version could be removed as @hoppfrosch suggests https://github.com/ahkscript/awesome-AutoHotkey/issues/21#issuecomment-163147292

**Comment by joedf** [comment]
About #21, I'm still waiting on what others think about removing the HTML version. :monkey:

**Comment by hoppfrosch** [comment]
#21 is done - I removed gh_pages

**Comment by vasili111** [comment]
1. No other awesome lists have autor names. I don't think mentioning author will bring something useful information to the reader. I think awesome list should be awesome first of all to the reader and it should not contain information that he dont needs. If someone wants to see author he can just follow link and see actual author name.
2. Aso there is a code that have several authors and we can't mention them all.

I think it is better to remove authors.

**Comment by vasili111** [comment]
It will be nice if more people will state their opinion about should we keep authors or not.

**Comment by joedf** [comment]
I think keeping the Authors is fine, and is a sort of "tip of the hat" or "kudos" to them. :+1:

**Comment by hoppfrosch** [comment]
As we currently have no objections against mentioning the authors I consider the current state as accepted.
