### ISSUE TITLE
Historical: VIC

### ISSUE THREAD

**Issue by hi5** [ahkscript/awesome-AutoHotkey#55]
Very good program (ANSI, AHK 1.0) only, but a "regular" text editor so not directly suitable for "Integrated Development Environment" as it is not focused on AHK. Not sure which category to use here.

Vic - A free text editor based on HiEdit control 
http://autohotkey.com/board/topic/48796-vic-a-free-text-editor-based-on-hiedit-control/

**Comment by joedf** [comment]
Cool homepage for it here too: http://normandlamoureux.com/vic/Vic_En.html

**Comment by hoppfrosch** [comment]
+

**Comment by hi5** [comment]
Perhaps make a new sub-section under Scripts named Others, there is a Tools - Others so Scripts - Others would work I think. It could be added to the normal Awesome list if a note is added its ANSI only.

**Comment by joedf** [comment]
I think that VIC could still fit in the normal one. Objections?

**Comment by hoppfrosch** [comment]
I'm not quite sure, if this still fits into normal one, since it relies on HIEDIT-Control which is 32-bit only, over 6years old now and not developed anymore ... (http://www.winasm.net/free-small-fast-text-editor.html).
Though VIC makes excellent use of HiEdit-Control, VIC itself is also not developed anymore.....

**Comment by joedf** [comment]
Ahh ok. Well said. Agreed.
